name: chatting_ui
description: A chat application for Corpa

# Prevent accidental publishing
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP networking
  http: ^1.2.0

  # State management
  provider: ^6.1.1

  # JWT decoding
  jwt_decoder: ^2.0.1

  # Secure storage for tokens
  flutter_secure_storage: ^9.0.0

  # Icons
  cupertino_icons: ^1.0.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png
    - assets/from_kel1.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf